templates_directory: templates/
template_file: default.jinja2
site_title: Test MB

plugins:
    module:
        - contentmakeup.markup.markdown
        - contentmakeup.strategy.app_runner
        - contentmakeup.strategy.binding_specs
        - contentmakeup.strategy.content_parser
        - contentmakeup.strategy.format_discovery
        - contentmakeup.strategy.input_reader
        - contentmakeup.strategy.metadata_extractor
        - contentmakeup.strategy.object_merger
        - contentmakeup.strategy.output_writer
        - contentmakeup.strategy.plugin_manager
        - contentmakeup.strategy.template_renderer
        - contentmakeup.strategy.template_discovery
        - contentmakeup.template.html
        - contentmakeup.template.jinja2
